---
- shell: ./01_fetch_data.sh ./data > 01_fetch_data.log 2>&1 \
         chdir={{ dbsnp_pg_min_root }}/contrib/freq

- become_user: dbsnp
  shell: ./02_drop_create_table.sh {{ dbsnp_builds }} {{ database_user }} . > 02_drop_create_table.log 2>&1 \
         chdir={{ dbsnp_pg_min_root }}/contrib/freq

- become_user: dbsnp
  shell: ./03_import_data.sh {{ dbsnp_builds }} {{ database_user }} . ./data > 03_import_data.log 2>&1 \
         chdir={{ dbsnp_pg_min_root }}/contrib/freq
  environment:
    PATH: "{{ ansible_env.PATH }}:/opt/pypy/bin"
