language: bash

before_install:
  - sudo apt-get update
  - sudo apt-get install nkf
  - sudo apt-get install pgtap
  - sudo /etc/init.d/postgresql stop
  - sudo /etc/init.d/postgresql start 9.4

before_script:
  - sudo -u postgres createuser -S -R -D -E -l dbsnp
  - sudo -u postgres createdb -E UTF8 -O dbsnp -hlocalhost dbsnp

script:
  - cd test; ./test.sh
