language: bash
addons:
    postgresql: "9.3"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install nkf -qq
  - sudo apt-get install pgtap
  - sudo /etc/init.d/postgresql stop
  - sudo /etc/init.d/postgresql start 9.3

before_script:
  - sudo -u postgres createuser -S -R -D -E -l dbsnp
  - sudo -u postgres createdb -E UTF8 -O dbsnp -hlocalhost test_dbsnp_pg_min
  - sudo ls /usr/share/postgresql
  - sudo ls
  - psql -U dbsnp -hlocalhost -d test_dbsnp_pg_min -f /usr/share/postgresql/9.3/extension/pgtap--*.sql
  - cd test; ./ci/before_script.sh test_dbsnp_pg_min dbsnp

script:
  - cd test; ./ci/script.sh test_dbsnp_pg_min

after_script:
  - cd test; ./ci/after_script.sh test_dbsnp_pg_min
