language: bash

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install nkf -qq
  - sudo apt-get install pgtap
  - sudo /etc/init.d/postgresql stop
  - sudo /etc/init.d/postgresql start 9.1
  - yes '' | sudo cpan -fi TAP::Parser::SourceHandler::pgTAP
  - export PATH=/home/travis/perl5/bin:$PATH
  - pg_prove --version

before_script:
  - createdb --owner=travis test_db
  - for x in /usr/share/postgresql/9.1/extension/pgtap--*.sql; do psql test_db -f $x; done
  - ./test/ci/before_script.sh test_db travis $PWD

script:
  - ./test/ci/script.sh        test_db travis $PWD

after_script:
  - ./test/ci/after_script.sh  test_db travis $PWD
