language: bash

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install nkf -qq
  - sudo apt-get install pgtap
  - sudo /etc/init.d/postgresql stop
  - sudo /etc/init.d/postgresql start 9.1

before_script:
  - sudo -u postgres createuser -S -R -D -E -l dbsnp
  - sudo -u postgres createdb -E UTF8 -O dbsnp -hlocalhost test_dbsnp_pg_min
  - psql -U dbsnp -hlocalhost -d test_dbsnp_pg_min -f `pg_config --sharedir`/extension/pgtap--*.sql
  - cd test; ./ci/before_script.sh test_dbsnp_pg_min dbsnp

script:
  - ./ci/script.sh test_dbsnp_pg_min

after_script:
  - ./ci/after_script.sh test_dbsnp_pg_min
