---
- name: create dbsnp user
  user: name={{ database_user }}
  become: yes

- name: create postgresql user for dbsnp
  become_user: postgres
  postgresql_user: name={{ database_user }}
                   role_attr_flags=NOSUPERUSER

- name: create postgresql database for dbsnp
  become_user: postgres
  postgresql_db: name={{ database_name }}
                 encoding='UTF-8'
                 owner={{ database_user }}

- name: install nkf
  yum: name=nkf state=present

- name: clone dbsnp-pg-min repo
  become_user: dbsnp
  git: repo=https://github.com/knmkr/dbsnp-pg-min.git
       dest={{ dbsnp_pg_min_root }}

- become_user: dbsnp
  shell: ./01_fetch_data.sh -d {{ dbsnp_builds }} -r {{ reference_genome_builds }} {{ dbsnp_pg_min_root }}/data > 01_fetch_data.log 2>&1 \
         chdir={{ dbsnp_pg_min_root }}

- become_user: dbsnp
  shell: ./02_drop_create_table.sh {{ database_name }} {{ database_user }} {{ dbsnp_pg_min_root }} > 02_drop_create_table.log 2>&1 \
         chdir={{ dbsnp_pg_min_root }}

- become_user: dbsnp
  shell: ./03_import_data.sh {{ database_name }} {{ database_user }} {{ dbsnp_pg_min_root }} {{ dbsnp_pg_min_root }}/data > 03_import_data.log 2>&1 \
         chdir={{ dbsnp_pg_min_root }}
