---
- hosts: 127.0.0.1
  connection: local
  become: yes
  gather_facts: yes
  roles:
    - { role: pypy }
    - { role: postgresql }
    - { role: dbsnp_pg_min, tags: ['common','install']}
    - { role: vcftools }
    - { role: dbsnp_pg_min_freq }
